const modal=document.getElementById("quizModal");
const openButtons=[document.getElementById("openQuiz"),document.getElementById("openQuiz2")].filter(Boolean);
const closeQuiz=document.getElementById("closeQuiz");
const startQuiz=document.getElementById("startQuiz");
const sendLeadButton=document.getElementById("sendLead");
const screens={start:document.getElementById("quizStart"),question:document.getElementById("quizQuestion"),loading:document.getElementById("quizLoading"),result:document.getElementById("quizResult")};
const questions=[
{key:"goal",title:"Что сейчас важнее всего?",answers:[{text:"Быстро получить отклик / заявки / реакцию",value:"fast"},{text:"Показать уровень и вызвать доверие",value:"trust"},{text:"Вовлечь человека и прогреть к диалогу",value:"engage"},{text:"Собрать всё в понятную систему",value:"system"}]},
{key:"stage",title:"Что у вас уже есть?",answers:[{text:"Есть идея, но пока нет упаковки",value:"idea"},{text:"Есть продукт, но его сложно объяснить",value:"product"},{text:"Есть страница/материалы, но они не работают",value:"weak"},{text:"Есть поток, хочу усилить и автоматизировать",value:"flow"}]},
{key:"block",title:"Где сейчас больше всего теряется результат?",answers:[{text:"Люди не понимают ценность",value:"value"},{text:"Есть интерес, но нет заявки",value:"action"},{text:"Не хватает доверия и ощущения уровня",value:"trust"},{text:"Слишком много хаоса, нет связки",value:"chaos"}]},
{key:"tempo",title:"Какой темп вам сейчас ближе?",answers:[{text:"Быстрый запуск без лишнего",value:"quick"},{text:"Аккуратная упаковка и статус",value:"premium"},{text:"Интерактив, чтобы вовлечь клиента",value:"interactive"},{text:"Хочу рекомендацию, пока не понимаю",value:"recommend"}]}];
let current=0;let answersState={};
function showScreen(name){Object.values(screens).forEach(s=>s.classList.remove("active"));screens[name].classList.add("active")}
function updateProgress(v){document.getElementById("progressBar").style.width=`${v}%`}
function openModal(){modal.classList.add("open");current=0;answersState={};updateProgress(0);showScreen("start")}
function closeModal(){modal.classList.remove("open")}
function renderQuestion(){const q=questions[current];document.getElementById("stepText").textContent=`${current+1} из ${questions.length}`;document.getElementById("questionTitle").textContent=q.title;const box=document.getElementById("answers");box.innerHTML="";q.answers.forEach(a=>{const b=document.createElement("button");b.type="button";b.textContent=a.text;b.onclick=()=>{answersState[q.key]=a.value;current++;updateProgress((current/questions.length)*100);current<questions.length?renderQuestion():showLoading()};box.appendChild(b)});showScreen("question")}
function showLoading(){showScreen("loading");document.body.style.cursor="progress";setTimeout(()=>{document.body.style.cursor="default";showResult()},1300)}
function getResult(){const{goal,stage,block,tempo}=answersState;if(goal==="engage"||tempo==="interactive")return{title:"Похоже, вам нужен не просто экран, а вовлечение",product:"Квиз / диагностика / интерактив / мини-сервис",text:"Ваша точка результата — включить человека в процесс. Здесь важно не просто рассказать, а дать человеку пройти маленький путь и почувствовать, что решение касается именно его."};if(goal==="trust"||block==="trust"||tempo==="premium")return{title:"Сейчас важнее усилить восприятие и доверие",product:"Портфолио / экспертная упаковка / презентационная страница",text:"Вам нужно не больше информации, а более сильная подача. Решение должно показать уровень, сформировать доверие и объяснить ценность до первого диалога."};if(goal==="system"||stage==="flow"||block==="chaos")return{title:"Вам нужна связка, где всё работает вместе",product:"Лендинг + квиз / интерактив + сбор лидов / AI-ассистент",text:"Один инструмент может быть слабым, если он не встроен в путь. Здесь лучше собрать сценарий: что человек видит, что делает дальше и как вы получаете более тёплый контакт."};return{title:"Сейчас лучше начать с быстрого и точного запуска",product:"Фокус-страница / лендинг / промо-запуск",text:"Ваша задача — быстро проверить отклик и не перегружать человека. Лучше собрать ясный вход, сильный оффер и один понятный следующий шаг."}}
function showResult(){const r=getResult();document.getElementById("resultTitle").textContent=r.title;document.getElementById("resultText").textContent=r.text;document.getElementById("resultProduct").textContent=r.product;showScreen("result")}
function sendLead(){const name=document.getElementById("clientName").value.trim();const contact=document.getElementById("clientContact").value.trim();const consent=document.getElementById("privacyConsent");const product=document.getElementById("resultProduct").textContent;const title=document.getElementById("resultTitle").textContent;if(!name||!contact){alert("Заполните имя и контакт, чтобы я могла ответить.");return}if(!consent.checked){alert("Поставьте галочку согласия на обработку персональных данных.");return}const msg=`Привет, Татьяна! Я прошла диагностику.%0A%0AИмя: ${encodeURIComponent(name)}%0AКонтакт: ${encodeURIComponent(contact)}%0AРезультат: ${encodeURIComponent(title)}%0AФормат: ${encodeURIComponent(product)}%0A%0AХочу обсудить решение под мою задачу.`;window.open(`https://t.me/tatishablin?text=${msg}`,"_blank")}
openButtons.forEach(b=>b.addEventListener("click",openModal));closeQuiz.addEventListener("click",closeModal);startQuiz.addEventListener("click",renderQuestion);sendLeadButton.addEventListener("click",sendLead);modal.addEventListener("click",e=>{if(e.target===modal)closeModal()});document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});
const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add("visible")})},{threshold:.16});document.querySelectorAll(".reveal").forEach(el=>observer.observe(el));
